---
# Ansible collections dung cho do an.
# Cai: ansible-galaxy collection install -r requirements.yml
collections:
  - name: ansible.netcommon
    version: ">=5.0.0"
  - name: nokia.srlinux
    version: ">=0.2.0"
