---
# Ket noi Ansible toi Nokia SR Linux (JSON-RPC qua HTTPAPI)
ansible_connection: ansible.netcommon.httpapi
ansible_network_os: nokia.srlinux.srlinux
ansible_user: admin
ansible_password: "NokiaSrl1!"
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 443
