---
# Role routing — KB-03: cau hinh dinh tuyen BGP
- name: "[routing] Cau hinh BGP cho SR Linux"
  ansible.builtin.include_tasks: srlinux.yml
  when: "'srlinux' in group_names"

- name: "[routing] Cau hinh BGP cho FRR"
  ansible.builtin.include_tasks: frr.yml
  when: "'frr' in group_names"
